version: '3.7'

services:
  nginx:
    image: nginx:1.16.1
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
      - ${PROJECT_PATH}:/var/www/html
    networks:
      - app
  php:
    build: './docker-file/php-fpm'
    image: dylanops/php-dev:7.4
    restart: always
    container_name: php
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    environment:
      PHP_IDE_CONFIG: 'serverName=web'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app
    ports:
      - "9000:9000"
  mysql:
    image: mariadb:10.4-focal
    container_name: mysql
    volumes:
      - ./backup:/var/backup
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app
    ports:
      - "3306:3306"
networks:
  app:
    driver: bridge